### ISSUE TITLE
Incompatible with Meteor 1.2rc7; package.js:18:9: Duplicate source file: csv-client.js (at Npm.depends.byline)

### ISSUE THREAD

**Issue by ljack** [evaisse/meteor-csv#4]
Just to let you know: 
ljack1@pim:~/workspace (meteor-1.2-rc7) $ meteor -p$IP:$PORT
[[[[[ ~/workspace ]]]]]                       

=> Started proxy.  
=> Errors prevented startup:                  

   While reading package from `/home/ubuntu/workspace/packages/meteor-csv`:
   package.js:18:9: Duplicate source file: csv-client.js (at Npm.depends.byline)

=> Your application has errors. Waiting for file change.

See also similar https://github.com/meteor/meteor/issues/5040

**Comment by evaisse** [comment]
Yeah indeed thanks
